# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 300))
        self.gridLayoutWidget = QtWidgets.QWidget(MainWindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 981, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.hintsCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.hintsCheckBox.setObjectName("hintsCheckBox")
        self.gridLayout.addWidget(self.hintsCheckBox, 2, 1, 1, 1)
        self.exitButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.exitButton.setMinimumSize(QtCore.QSize(120, 30))
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 4, 1, 1, 1)
        self.playButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.playButton.setMinimumSize(QtCore.QSize(120, 30))
        self.playButton.setObjectName("playButton")
        self.gridLayout.addWidget(self.playButton, 4, 0, 1, 1)
        self.matchThePicRadioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.matchThePicRadioButton.setMinimumSize(QtCore.QSize(120, 30))
        self.matchThePicRadioButton.setObjectName("matchThePicRadioButton")
        self.gridLayout.addWidget(self.matchThePicRadioButton, 2, 0, 1, 1)
        self.multipleChoiceGameRadioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.multipleChoiceGameRadioButton.setMinimumSize(QtCore.QSize(120, 30))
        self.multipleChoiceGameRadioButton.setChecked(True)
        self.multipleChoiceGameRadioButton.setObjectName("multipleChoiceGameRadioButton")
        self.gridLayout.addWidget(self.multipleChoiceGameRadioButton, 0, 0, 1, 1)
        self.derDieOderDasRadioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.derDieOderDasRadioButton.setMinimumSize(QtCore.QSize(120, 30))
        self.derDieOderDasRadioButton.setObjectName("derDieOderDasRadioButton")
        self.gridLayout.addWidget(self.derDieOderDasRadioButton, 1, 0, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 120)
        self.gridLayout.setColumnMinimumWidth(1, 120)
        self.gridLayout.setRowMinimumHeight(0, 30)
        self.gridLayout.setRowMinimumHeight(1, 30)
        self.gridLayout.setRowMinimumHeight(2, 30)
        self.gridLayout.setRowMinimumHeight(3, 30)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vocabulary Practice!"))
        self.hintsCheckBox.setText(_translate("MainWindow", "Hints?"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.playButton.setText(_translate("MainWindow", "Play!"))
        self.matchThePicRadioButton.setText(_translate("MainWindow", "Match the Picture"))
        self.multipleChoiceGameRadioButton.setText(_translate("MainWindow", "Multiple Choice"))
        self.derDieOderDasRadioButton.setText(_translate("MainWindow", "Der, Die oder Das?"))
